### ISSUE TITLE
Fix peers sync

### ISSUE THREAD

**Issue by cytadela8** [aeternity/elixir-research#129]
3 nodes test (4001, 4002, 4003) where 4002 knows 4001 and 4003 known 4002 showed problems with peers. 4002 when trying to sync peers produces following error:

```
[error] GenServer Aecore.Peers.Worker terminating
** (ArgumentError) argument error                                                    
    (aehttpclient) lib/client.ex:13: Aehttpclient.Client.get_info/1                  
    (aecore) lib/aecore/peers/worker.ex:174: Aecore.Peers.Worker.check_peer/2        
    (aecore) lib/aecore/peers/worker.ex:84: Aecore.Peers.Worker.handle_call/3        
    (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4                       
    (stdlib) gen_server.erl:665: :gen_server.handle_msg/6                            
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3                           
Last message (from Aecore.Peers.Sync): {:add_peer, {"localhost:4001", "C061E48A6F7FB2634E0C012B168D41F4773A38BD9E5EA28E5BE7D04186127BA0"}}                                
State: %{nonce: 523457149, peers: %{"localhost:4002" => "C061E48A6F7FB2634E0C012B168D41F4773A38BD9E5EA28E5BE7D04186127BA0"}}                                              
Client Aecore.Peers.Sync is alive                                                    
    (stdlib) gen.erl:169: :gen.do_call/4                                             
    (elixir) lib/gen_server.ex:771: GenServer.call/3                                 
    (aecore) lib/aecore/peers/sync.ex:101: anonymous fn/2 in Aecore.Peers.Sync.get_newpeers_and_add/1                                                                     
    (elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3                   
    (aecore) lib/aecore/peers/sync.ex:66: Aecore.Peers.Sync.refill/0                 
    (aecore) lib/aecore/peers/sync.ex:25: Aecore.Peers.Sync.handle_info/2            
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4                          
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6                            
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3                           

[error] GenServer Aecore.Peers.Sync terminating                                      
** (stop) exited in: GenServer.call(Aecore.Peers.Worker, {:add_peer, {"localhost:4001", "C061E48A6F7FB2634E0C012B168D41F4773A38BD9E5EA28E5BE7D04186127BA0"}}, 10000)      
    ** (EXIT) an exception was raised:                                               
        ** (ArgumentError) argument error                                            
            (aehttpclient) lib/client.ex:13: Aehttpclient.Client.get_info/1          
            (aecore) lib/aecore/peers/worker.ex:174: Aecore.Peers.Worker.check_peer/2                                                                                     
            (aecore) lib/aecore/peers/worker.ex:84: Aecore.Peers.Worker.handle_call/3                                                                                     
            (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4               
            (stdlib) gen_server.erl:665: :gen_server.handle_msg/6                    
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3                   
    (elixir) lib/gen_server.ex:774: GenServer.call/3                                 
    (aecore) lib/aecore/peers/sync.ex:101: anonymous fn/2 in Aecore.Peers.Sync.get_newpeers_and_add/1                                                                     
    (elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3                   
    (aecore) lib/aecore/peers/sync.ex:66: Aecore.Peers.Sync.refill/0                 
    (aecore) lib/aecore/peers/sync.ex:25: Aecore.Peers.Sync.handle_info/2            
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4                          
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6                            
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3                           
Last message: :work                                                                  
State: %{}
```

**Comment by d-velev** [comment]
We fixed this in the #97 PR, the issue is {"localhost:4001", "C061E48A6F7FB2634E0C012B168D41F4773A38BD9E5EA28E5BE7D04186127BA0"} was being passed  to add_peer when we should only be passing "localhost:4001"

**Comment by cytadela8** [comment]
Thanks for pointing that out. I found the commit cd1dbfbd52ef0250d9980dcabd014d8d3abd4600

**Comment by cytadela8** [comment]
I actually have a little bit different fix that I prefer, so we will have to solve a conflict when merging your work
