### ISSUE TITLE
broken sync /new_block

### ISSUE THREAD

**Issue by thepiwo** [aeternity/elixir-research#218]
```
[error] #PID<0.557.0> running Aehttpserver.Web.Endpoint terminated
Server: 127.0.0.1:4000 (http)
Request: POST /new_block
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Keyword.fetch!/2
        (elixir) lib/keyword.ex:368: Keyword.fetch!({[{Plug.Parsers.URLENCODED, [length: 1000000, json_decoder: Poison]}, {Plug.Parsers.MULTIPART, [json_decoder: Poison]}, {Plug.Parsers.JSON, [json_decoder: Poison]}], ["*/*"], 1000000}, :parsers)
        (plug) lib/plug/parsers.ex:207: Plug.Parsers.call/2
        (aehttpserver) lib/aehttpserver/web/endpoint.ex:1: Aehttpserver.Web.Endpoint.plug_builder_call/2
        (aehttpserver) lib/plug/debugger.ex:99: Aehttpserver.Web.Endpoint."call (overridable 3)"/2
        (aehttpserver) lib/aehttpserver/web/endpoint.ex:1: Aehttpserver.Web.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /home/philipp/Develop/elixir-research/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

**Comment by thepiwo** [comment]
solved by removing and redownloading dependencies
